const YELLOW_COLOR = '#FFE300';
const LIGHT_BLUE_COLOR = '#4BD5EE';
const WHITE_COLOR = '#FFF';
const DARK_GREY_COLOR = '#333';
const BLACK_COLOR = '#000';
const BEIGE_COLOR = '#EFF2F7';
const LIGHT_GREY_COLOR = '#E5E9F2';
const GREY_COLOR = '#3C4858';
const GREY_1_COLOR = '#273444';

export {
  WHITE_COLOR,
  YELLOW_COLOR,
  LIGHT_BLUE_COLOR,
  LIGHT_GREY_COLOR,
  DARK_GREY_COLOR,
  BEIGE_COLOR,
  GREY_COLOR,
  GREY_1_COLOR,
  BLACK_COLOR,
};
