const DEFAULT_BACKGROUND_COLOR_DARK_THEME = '#000';
const DEFAULT_FONT_COLOR_DARK_THEME = '#4E5B6E';

export default {
  backgroundColor: DEFAULT_BACKGROUND_COLOR_DARK_THEME,
  color: DEFAULT_FONT_COLOR_DARK_THEME,
};
