const DEFAULT_BACKGROUND_COLOR_LIGHT_THEME = '#E8EAED';
const DEFAULT_FONT_COLOR_LIGHT_THEME = '#ABB1BA';

export default {
  backgroundColor: DEFAULT_BACKGROUND_COLOR_LIGHT_THEME,
  color: DEFAULT_FONT_COLOR_LIGHT_THEME,
};
